### ISSUE TITLE
[Feature Request] Select until equal or greater indent level

### ISSUE THREAD

**Issue by aoyama-val** [haberdashPI/vscode-select-by-indent#4]
Hi, thanks for the extension. I love the idea 😃 
Here's my two cents: I would be better if we had the feature in title, for example,

```javascript
function foo() {
  for (let i = 0; i < 10; i++) { // put cursor on this line and execute the command
      console.log("hello");
  } // and three lines until here are selected
  return 1;
}
```

It's similar to `select-outer`, the only difference is you put cursor on `for` line or in `{}` block. But this way is more intuitive for me.
It would be appreciate if you could consider it.

**Comment by haberdashPI** [comment]
Hi there, I completely missed this issue in my notifications. My apologies.

So if I understand your request, it is to be able to select the indent region starting from the line just below the cursor location, and the two surrounding "outdented" lines. Is that right? Makes sense.

That should be easy to do!

**Comment by aoyama-val** [comment]
Thank you for the comment.

From: the line just below the cursor location
To: the first line which indent is less than or equal to that of the starting line.
I think it allows us to select a syntax block in many languages if the code is properly indented.

```javascript
function foo() { // NOT SELECTED
  for (let i = 0; i < 10; i++) { // put cursor on this line and execute the command  SELECTED
      console.log("hello");  // SELECTED
  } // SELECTED
  return 1;  // NOT SELECTED
}
```

**Comment by haberdashPI** [comment]
This feature has now been implemented! See the README for details.
