### ISSUE TITLE
command 'vscode-select-by-indent.select-outer-down' not found

### ISSUE THREAD

**Issue by aoyama-val** [haberdashPI/vscode-select-by-indent#6]
Maybe it is missing in `activationEvents`?
https://github.com/haberdashPI/vscode-select-by-indent/blob/master/package.json#L16

![image](https://user-images.githubusercontent.com/13144822/153372740-ababb11b-c020-40ac-bd43-8d053fe40e52.png)

**Comment by haberdashPI** [comment]
Mmm... 🤔 Let me look into this. Should be easy to fix. Sorry I did not notice this issue sooner.

**Comment by haberdashPI** [comment]
This should be closed in version 0.3.2. Let me know if you have any further problems!
